[programs.localnet]
marketplace = "fHuLXbJW45hJJmk8Ryi7mfopauynVRLnvB3yHNB64bA"
[programs.devnet]
marketplace = "fHuLXbJW45hJJmk8Ryi7mfopauynVRLnvB3yHNB64bA"
[programs.testnet]
marketplace = "fHuLXbJW45hJJmk8Ryi7mfopauynVRLnvB3yHNB64bA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "testnet"
wallet = "/root/.config/solana/id.json"
/root/.config/solana/devnet-wallet.json
/root/.config/solana/testnet-wallet.json

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/ignore_creators.ts"
